name: Report Tempurature

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
        
      - name: Update apt
        run: |
          sudo apt update

      - name: Install Chrome
        run: |
          wget --no-verbose https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y -f ./google-chrome-stable_current_amd64.deb

      - name: Install Chrome driver
        run: |
          version=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          wget -qP /tmp/ "https://chromedriver.storage.googleapis.com/${version}/chromedriver_linux64.zip"
          sudo unzip -o /tmp/chromedriver_linux64.zip -d /usr/bin
      
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install webdriver-manager
      
      - name: Report
        env:
          acc: ${{ secrets.acc }}
          pwd: ${{ secrets.pwd }}
        run: |
          python main.py $acc $pwd
