name: Report Tempurature

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
        
      - name: Update apt
        run: |
          sudo apt update

      # - name: Install Chrome
      #   run: |
      #     wget --no-verbose https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      #     sudo apt install -y -f ./google-chrome-stable_current_amd64.deb

      # - name: Install Chrome driver
      #   run: |
      #     version=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
      #     wget -qP /tmp/ "https://chromedriver.storage.googleapis.com/${version}/chromedriver_linux64.zip"
      #     sudo unzip -o /tmp/chromedriver_linux64.zip -d /usr/bin

      - name: Install Edge
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-stable.list'
          sudo rm microsoft.gpg
          sudo apt install microsoft-edge-stable

      - name: Install Edger driver
        run: |
          wget https://msedgedriver.azureedge.net/95.0.1020.5/edgedriver_linux64.zip -P ~/
          unzip ~/edgedriver_linux64.zip -d ~/
          rm ~/edgedriver_linux64.zip
          sudo mv -f ~/msedgedriver /usr/local/share/
          sudo chmod 777 /usr/local/share/msedgedriver
          sudo ln -s /usr/local/share/msedgedriver /usr/local/bin/msedgedriver
      
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install webdriver-manager
      
      - name: Report
        env:
          acc: ${{ secrets.acc }}
          pwd: ${{ secrets.pwd }}
        run: |
          python main.py $acc $pwd
